### ISSUE TITLE
Contribute to main OpenWrt package repo?

### ISSUE THREAD

**Issue by roger-** [WRTnode/openwrt-packages#1]
Hey,

Any interest in adding your packages to the main [OpenWrt packages repo](https://github.com/openwrt/packages)? I'm mostly interested in OpenCV myself.

Thanks!

**Comment by noello** [comment]
Hi Roger

That will be cool. But how we start?

**Comment by roger-** [comment]
Hi noello,

I just discovered your packages and haven't tested them myself. Do you know if they build ok under OpenWrt trunk?

If so then it's simple as opening a pull request. I can help with that if you like.

Cheers

**Comment by noello** [comment]
Hi

We've tested it in BB, tomorrow we will test in trunk and update with you, it's midnight in China now. :)

**Comment by roger-** [comment]
I took a quick look at the OpenCV makefile, and I think it might need the following small changes:
1. Link to the official download on SF (e.g. [from here](http://opencv.org/downloads.html)).
2. Update to 2.4.10 (if possible).
3. Exclude `/usr/include/*` from the main package (most people have no compiler and won't need the header files on their devices).
4. Add license type and maintainer info (all packages need this).

**Comment by lijpsummer** [comment]
Hi Roger

The modified opencv package has been uploaded, if there are any problem, contact us any time.

**Comment by noello** [comment]
Ps, we've tried in trunk. :)

**Comment by roger-** [comment]
Looks good!

Do you want to make the pull request?

**Comment by noello** [comment]
we are pulling now, https://github.com/openwrt/packages/pull/804

**Comment by roger-** [comment]
Great, thanks!
